- name: My first play
  hosts: myhosts
  become_user: root
  become: true
  become_method: sudo
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

    - name: Relax number of wrong passwords login attemps before locking out
      community.general.ini_file: # https://docs.ansible.com/ansible/latest/collections/community/general/ini_file_module.html
        path: /etc/security/faillock.conf
        option: deny
        value: 10
        state: present
        exclusive: true
        create: false

###########

    # https://github.com/ollama/ollama/blob/main/docs/linux.md
    - name: Ollama | Install package from extra
      community.general.pacman:
        name: ollama-rocm
        state: present
    - name: Ollama | Add user
      ansible.builtin.user:
        name: ollama
        comment:
        group: ollama
        shell: /bin/false
        create_home: true
        # home: /usr/share/ollama

    - name: Ollama | Create Unit file
      template: 
        src: ollama/ollama.service.j2
        dest: /etc/systemd/system/ollama.service
        mode: '644'

    - name: Ollama | Reload systemctl configuration and restart ollama.service
      ansible.builtin.systemd:
        daemon_reload: true
        name: ollama.service 
        enabled: true
        state: restarted

    # - name: Ollama | Run open-webui
    #   community.docker.docker_compose_v2:
    #     project_src: ./ansible/ollama
    #     state: present
    #     #docker_host: unix:///run/user/1000/podman/podman.sock
    #     docker_host: unix:///run/podman/podman.sock
    - name: Ollama | create open-webui
      containers.podman.podman_container:
        name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        state: quadlet
        #quadlet_dir: /home/toly/.config/containers/systemd/
        #quadlet_dir: /etc/containers/systemd/
        quadlet_file_mode: u=rw,g=r,o=r
        ports:
          - "127.0.0.1:3000:8080/tcp"
        volumes:
          - open-webui:/app/backend/data
        quadlet_options:
          - |
            [Install]
            WantedBy=default.target
            [Service]
#           User=toly
#           Group=toly

    - name: Ollama | Start open-webui
      ansible.builtin.systemd:
        daemon_reload: true
        name: open-webui.service
        enabled: true
        state: restarted


